name: googlemerr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  flutter_keyboard_visibility: ^6.0.0
  share: ^2.0.4
  video_player: ^2.9.2



  # Icons
  cupertino_icons: ^1.0.8

  # Utility Packages
  url_launcher: ^6.1.10
  image_picker: ^1.1.2  # Updated to the latest version
  flutter_typeahead: ^5.2.0  # Updated to the latest version
  shared_preferences: ^2.3.2

  # Localization Support
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7  # Make sure this is included

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated to the latest version

flutter:
  uses-material-design: true
  generate: true  # This should be enabled for localization

  assets:
    - assets/
    - assets/files/


# Add localization settings here
flutter_gen:
  localizations:
    arb-dir: lib/l10n               # Directory for ARB files
    template-arb-file: app_en.arb   # Default template ARB file
    output-localization-file: app_localizations.dart  # Output file for localization code
