name: googlemerr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  flutter_keyboard_visibility: ^6.0.0
  provider: ^6.0.0
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  video_player: ^2.9.2


  # Icons
  cupertino_icons: ^1.0.8

  # Utility Packages
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  flutter_typeahead: ^5.2.0
  shared_preferences: ^2.3.2

  # Localization Support
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  share_plus: ^10.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/         # Include other assets if needed
    - assets/files/

flutter_gen:
  localizations:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
